version: "3.3"

services:
  db:
    restart: always
    image: postgres
    container_name: demo-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    container_name: demo-pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
  web:
    build: .
    container_name: djangoappp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/analyzeMyMood
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: