# Generated by Django 3.1.5 on 2021-01-23 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('time_interval', models.CharField(default='', max_length=50)),
                ('tweet_count', models.CharField(default='', max_length=10)),
                ('keyword', models.CharField(default='', max_length=50)),
                ('hashtag', models.CharField(default='', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(default='', max_length=100)),
                ('creation_date', models.CharField(default='', max_length=100)),
                ('tweet_text', models.TextField(default='')),
                ('sentiment', models.CharField(default='', max_length=10)),
                ('lang', models.CharField(default='', max_length=10)),
                ('retweet_count', models.CharField(default='', max_length=10)),
                ('reply_count', models.CharField(default='', max_length=10)),
                ('like_count', models.CharField(default='', max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(default='')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='ContextAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(default='', max_length=100)),
                ('domain_name', models.CharField(default='', max_length=100)),
                ('domain_desc', models.CharField(default='', max_length=250)),
                ('entity_id', models.CharField(default='', max_length=100)),
                ('entity_name', models.CharField(default='', max_length=100)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.tweet')),
            ],
        ),
    ]
