# Generated by Django 3.1.5 on 2021-01-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='language',
            field=models.CharField(default='', max_length=10),
        ),
    ]
