# Generated by Django 3.1.5 on 2021-01-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='hashtag_string',
            field=models.TextField(default=''),
        ),
    ]
