# Generated by Django 3.1.5 on 2021-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_tweet_hashtag_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='context_string',
            field=models.TextField(default=''),
        ),
    ]
