# Generated by Django 3.1.5 on 2021-01-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_tweet_context_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='context_string',
            new_name='context_domain_string',
        ),
    ]
