# Generated by Django 3.1.5 on 2021-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20210127_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='context_entity_string',
            field=models.TextField(default=''),
        ),
    ]
