# Generated by Django 3.1.5 on 2021-01-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_tweet_context_entity_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
