# Generated by Django 3.1.5 on 2021-02-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20210129_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextannotation',
            name='domain_desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contextannotation',
            name='domain_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contextannotation',
            name='entity_name',
            field=models.TextField(default=''),
        ),
    ]
